server:
  port: 9101
spring:
  profiles:
    active: dev
  application:
    name: micro-react-file-management
  cloud:
    nacos:
      discovery:
        server-addr: 47.102.36.32:8848
#        指定外网ip 不同服务器上部署的微服务模块需要指定这个配置
        ip: 121.36.49.252
        port: 9101
# 访问图片的ip地址
image:
 url: http://121.36.49.252:9101/image/

# 访问文件的ip地址
file:
  url: http://121.36.49.252:9101/file/
