server:
  port: 9001
spring:
  profiles:
    active: dev
  application:
    name: micro-react-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.102.36.32:8848
    gateway:
      routes: #配置路由路径
        - id: micro-react-file-management
          uri: lb://micro-react-file-management
          predicates:
            - Path=/file-management/**
          filters:
            - StripPrefix=1
        - id: micro-react-sso
          uri: lb://micro-react-sso
          predicates:
            - Path=/sso/**
          filters:
            - StripPrefix=1
        - id: micro-react-mail
          uri: lb://micro-react-mail
          predicates:
            - Path=/mail/**
          filters:
            - StripPrefix=1
        - id: micro-react-admin
          uri: lb://micro-react-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
