server:
  port: 9501
spring:
  profiles:
    active: dev
  application:
    name: micro-react-admin
  cloud:
    nacos:
      discovery:
        server-addr: 121.36.8.146:8848
#        指定外网ip
        ip: 121.36.49.252
        port: 9501
  main:
    allow-bean-definition-overriding: true
  # 数据库
  datasource:
    druid:
      url: jdbc:mysql://121.36.8.146:3306/micro_blog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000

mybatis:
  mapper-locations: classpath:mapper/*.xml

# pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  offset-as-page-num: true
  row-bounds-with-count: true
  page-size-zero: true
